# Generated by Django 5.0.6 on 2024-05-26 12:03

import uuid

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("identity_number", models.CharField(max_length=11)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
