# Generated by Django 5.0.6 on 2024-06-05 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="surname",
            new_name="last_name",
        ),
    ]
