# Generated by Django 5.0.6 on 2024-06-06 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_rename_name_customer_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="identity_number",
        ),
    ]
