# Generated by Django 5.0.6 on 2024-05-26 12:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SparePart",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("amount", models.PositiveSmallIntegerField()),
                ("left_amount", models.PositiveSmallIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
