# Generated by Django 5.0.6 on 2024-06-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spare_part", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepart",
            name="temp_amount",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
