# Generated by Django 5.0.6 on 2024-06-06 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spare_part", "0004_alter_model_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepart",
            name="brand",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spare_parts",
                to="spare_part.brand",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sparepart",
            name="model",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spare_parts",
                to="spare_part.model",
            ),
            preserve_default=False,
        ),
    ]
